accent = "#509475"
cursor = "#d7c995"
foreground = "#c1c497"
background = "#111c18"
selection_foreground = "#111c18"
selection_background = "#c1c497"

color0 = "#23372b"
color1 = "#ff5345"
color2 = "#549e6a"
color3 = "#459451"
color4 = "#509475"
color5 = "#d2689c"
color6 = "#2dd5b7"
color7 = "#f6f5dd"
color8 = "#53685b"
color9 = "#db9f9c"
color10 = "#63b07a"
color11 = "#e5c736"
color12 = "#acd4cf"
color13 = "#75bbb3"
color14 = "#8cd3cb"
color15 = "#9eebb3"
