background = #111c18
foreground = #c1c497
cursor-color = #d7c995
selection-background = #c1c497
selection-foreground = #111c18

palette = 0=#23372b
palette = 1=#ff5345
palette = 2=#549e6a
palette = 3=#459451
palette = 4=#509475
palette = 5=#d2689c
palette = 6=#2dd5b7
palette = 7=#f6f5dd
palette = 8=#53685b
palette = 9=#db9f9c
palette = 10=#63b07a
palette = 11=#e5c736
palette = 12=#acd4cf
palette = 13=#75bbb3
palette = 14=#8cd3cb
palette = 15=#9eebb3

macos-icon = custom-style
macos-icon-ghost-color = #509475
macos-icon-screen-color = #111c18
