#!/usr/bin/env node
/**
 * Convert an animated GIF into palette-indexed half-block frames for the
 * nicknisi-header pi extension.
 *
 * Usage: node gen-frames.mjs <input.gif> <output.ts> [cols] [pxHeight]
 *
 * Each terminal cell holds two vertical pixels: fg = top pixel, bg = bottom
 * pixel, glyph = ▀ (both set / top only) or ▄ (bottom only). Transparent
 * pixels become plain spaces so the terminal background shows through.
 *
 * Output format (decoded by index.ts):
 *   COLORS: [r,g,b][]            — index 0 is reserved for "transparent"
 *   CELLS:  [fgIdx, bgIdx][]     — index 0 is reserved for a space
 *   FRAMES: { delay, lines }[]   — lines are arrays of "cellIdx" or "cellIdx*run"
 */

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const [gif, out, colsArg, pxHArg] = process.argv.slice(2);
if (!gif || !out) {
	console.error("usage: node gen-frames.mjs <input.gif> <output.ts> [cols] [pxHeight]");
	process.exit(1);
}
const COLS = Number(colsArg ?? 40);
const PX_H = Number(pxHArg ?? 44);

const frameCount = execFileSync("magick", ["identify", gif]).toString().trim().split("\n").length;
const delays = execFileSync("magick", ["identify", "-format", "%T,", gif])
	.toString()
	.split(",")
	.filter(Boolean)
	.map((d) => Math.max(Number(d) * 10, 20)); // GIF delays are 1/100s → ms

// color palette: index 0 = transparent
const colorToIdx = new Map();
const COLORS = [[0, 0, 0]];
const colorIdx = (r, g, b) => {
	const key = (r << 16) | (g << 8) | b;
	let idx = colorToIdx.get(key);
	if (idx === undefined) {
		idx = COLORS.length;
		COLORS.push([r, g, b]);
		colorToIdx.set(key, idx);
	}
	return idx;
};

// cell palette: index 0 = space
const cellToIdx = new Map();
const CELLS = [[0, 0]];
const cellIdx = (fg, bg) => {
	const key = `${fg},${bg}`;
	let idx = cellToIdx.get(key);
	if (idx === undefined) {
		idx = CELLS.length;
		CELLS.push([fg, bg]);
		cellToIdx.set(key, idx);
	}
	return idx;
};

// One coalesced pass: partial (delta-optimized) GIF frames are composited
// onto earlier ones, and all frames come back as a single concatenated buffer.
const raw = execFileSync(
	"magick",
	[gif, "-coalesce", "-resize", `${COLS}x${PX_H}!`, "-depth", "8", "rgba:-"],
	{ encoding: "buffer", maxBuffer: 64 * 1024 * 1024 },
);
const frameSize = COLS * PX_H * 4;
if (raw.length !== frameCount * frameSize) {
	console.error(`expected ${frameCount * frameSize} bytes, got ${raw.length}`);
	process.exit(1);
}

const frames = [];
for (let f = 0; f < frameCount; f++) {
	const buf = raw.subarray(f * frameSize, (f + 1) * frameSize);
	const px = (x, y) => {
		const o = (y * COLS + x) * 4;
		return buf[o + 3] < 128 ? 0 : colorIdx(buf[o], buf[o + 1], buf[o + 2]);
	};

	const lines = [];
	for (let y = 0; y < PX_H; y += 2) {
		// build cells for this terminal row
		const row = [];
		for (let x = 0; x < COLS; x++) {
			const top = px(x, y);
			const bottom = px(x, y + 1);
			row.push(top === 0 && bottom === 0 ? 0 : cellIdx(top, bottom));
		}
		// trim trailing spaces, then RLE encode
		while (row.length && row[row.length - 1] === 0) row.pop();
		const tokens = [];
		for (let i = 0; i < row.length; i++) {
			let run = 1;
			while (i + run < row.length && row[i + run] === row[i]) run++;
			tokens.push(run > 1 ? `${row[i]}*${run}` : `${row[i]}`);
			i += run - 1;
		}
		lines.push(tokens);
	}
	// trim fully-empty top/bottom rows on frame 0 only shape-wise; keep all rows
	// so every frame has identical dimensions (stable header height)
	frames.push({ delay: delays[f] ?? 100, lines });
}

const ts = `// Generated by gen-frames.mjs from ${gif.split("/").pop()} — do not edit by hand.
// ${frameCount} frames, ${COLS}x${PX_H / 2} cells, ${COLORS.length - 1} colors, ${CELLS.length - 1} cells.
export const COLORS: [number, number, number][] = ${JSON.stringify(COLORS)};
export const CELLS: [number, number][] = ${JSON.stringify(CELLS)};
export const FRAMES: { delay: number; lines: string[][] }[] = ${JSON.stringify(frames)};
`;
writeFileSync(out, ts);

const kb = (ts.length / 1024).toFixed(0);
console.log(`wrote ${out}: ${frameCount} frames, ${COLORS.length - 1} colors, ${CELLS.length - 1} cells, ${kb}KB`);
