accent = "#D1FFb0"
cursor = "#E25F4B"
foreground = "#e6f6f0"
background = "#00110b"
selection_foreground = "#00110b"
selection_background = "#E25F4B"

color0 = "#00110b"
color1 = "#ff3370"
color2 = "#00a86b"
color3 = "#D1FFb0"
color4 = "#FF6600"
color5 = "#8fc85c"
color6 = "#80d4b5"
color7 = "#FFF7F2"
color8 = "#3E6650"
color9 = "#ff3370"
color10 = "#00a86b"
color11 = "#D1FFb0"
color12 = "#FF6600"
color13 = "#8fc85c"
color14 = "#80d4b5"
color15 = "#e6f6f0"
