mode = "dark"

accent = "#d1ffb0"
muted = "#3e6650"

background = "#00110b"
dark_background = "#00110b"
darker_background = "#000c06"
lighter_background = "#0c1d17"

foreground = "#e6f6f0"
dark_foreground = "#98c48f"
light_foreground = "#f4fbf7"
bright_foreground = "#e6f6f0"

red = "#ff3370"
yellow = "#d1ffb0"
orange = "#ff6600"
green = "#00a86b"
cyan = "#80d4b5"
blue = "#ff6600"
magenta = "#8fc85c"

bright_red = "#ff3370"
bright_yellow = "#d1ffb0"
bright_green = "#00a86b"
bright_cyan = "#80d4b5"
bright_blue = "#ff6600"
bright_magenta = "#8fc85c"

cursor = "#e25f4b"
selection_foreground = "#00110b"
selection_background = "#e25f4b"

color0 = "#00110b"
color1 = "#ff3370"
color2 = "#00a86b"
color3 = "#d1ffb0"
color4 = "#ff6600"
color5 = "#8fc85c"
color6 = "#80d4b5"
color7 = "#fff7f2"
color8 = "#3e6650"
color9 = "#ff3370"
color10 = "#00a86b"
color11 = "#d1ffb0"
color12 = "#ff6600"
color13 = "#8fc85c"
color14 = "#80d4b5"
color15 = "#e6f6f0"
