background = #00110b
foreground = #e6f6f0
cursor-color = #E25F4B
selection-background = #E25F4B
selection-foreground = #00110b

palette = 0=#00110b
palette = 1=#ff3370
palette = 2=#00a86b
palette = 3=#D1FFb0
palette = 4=#FF6600
palette = 5=#8fc85c
palette = 6=#80d4b5
palette = 7=#FFF7F2
palette = 8=#3E6650
palette = 9=#ff3370
palette = 10=#00a86b
palette = 11=#D1FFb0
palette = 12=#FF6600
palette = 13=#8fc85c
palette = 14=#80d4b5
palette = 15=#e6f6f0

macos-icon = custom-style
macos-icon-ghost-color = #D1FFb0
macos-icon-screen-color = #00110b
