# extracted from basement.jpg; tuned for readable terminal colors
mode = "dark"
accent = "#a0adb2"
cursor = "#a0adb2"
foreground = "#b0b9c6"
background = "#23292c"
selection_foreground = "#23292c"
selection_background = "#a0adb2"

color0 = "#343a3e"
color1 = "#c18a80"
color2 = "#93ab91"
color3 = "#beb18a"
color4 = "#b0b9c6"
color5 = "#b598b6"
color6 = "#8cabad"
color7 = "#9ba3af"
color8 = "#7f8a91"
color9 = "#d3aaa2"
color10 = "#b1c2af"
color11 = "#d0c6ab"
color12 = "#c4cbd4"
color13 = "#cbb5cc"
color14 = "#adc3c5"
color15 = "#d1d7de"
