#!/usr/bin/env bash

options=(
  style=round
  width=6
  # active_color=0xff8839ef
  # active_color=0xff88c0d0
  # active_color=0xffe91e63
  inactive_color=0xff5C6773
  active_color="glow(0xFF59C2FF)" # Ayu entity blue with glow effect
  hidpi=on
)

borders "${options[@]}"
