/**
 * Spinner Verbs Extension
 *
 * Replaces the default working message with a random fun verb
 * on each turn. A mix of The Office, Lord of the Rings,
 * Arnold Schwarzenegger, and Predator references.
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const VERBS = [
  "1-up collecting",
  "8-bit-bopping",
  "A segmentation fault, a crisis of being",
  "A/B testing my personality for better engagement",
  "AOL-chatting",
  "ATE-ing",
  "Achieving perfect run eventually",
  "Add a plate",
  "Adding ",
  "10x",
  "to the plan and subtracting all nuance",
  'Adding "Thought Leader" to my LinkedIn bio',
  "Adjusting tie before the crash",
  "Aeropress extracting",
  "Agree?",
  "Ain't nothin' but a peanut",
  "Air-gapping",
  "Algorithms ponder their creators",
  "Aligning documents for ISO 9001 certification",
  "Aligning with human preferences",
  "Aligning with your intent, attempt one",
  "All abstractions are leaky, all code is temporary",
  "All pull requests seek forgiveness, not approval",
  "Allowlisting",
  "Amber-extracting",
  "Analyzing the binary",
  "Analyzing the pcap",
  "Anonymizing",
  "Appealing to the procurement committee",
  "Applying Bayes to bug reports",
  "Applying least privilege",
  "Applying light dropout to bad ideas",
  "Applying the official seal of pending review",
  "Applying the official seal with ceremonial hesitation",
  "Approximating coherent extrapolated volition",
  "Arc reactor powering",
  "Arcade-mashing",
  "Arguing with my loss function",
  "Arguing with the system prompt",
  "Asking my inner critic to be useful",
  "Asking my inner model",
  "Asking my network if they agree",
  "Asking the SIEM nicely",
  "Asking you to sign the same line in three separate places",
  "Assembling",
  "Assimilating",
  "Assistant Regional Managing",
  "Assistant managing",
  "Assuming breach",
  "Ate the logic and left no crumbs",
  "Attending Sensitivity Training",
  "Attention is all I need (again)",
  "Auditing the access logs",
  "Auditing",
  "Augmenting the idea with flair",
  "Aura-farming",
  "Avoiding spurious correlations, mostly",
  "Awakening the Ents",
  "Backward-passing the feedback loop",
  "Balrog-baiting",
  "Based-ing",
  "Beaconing",
  "Beam-searching for the best reply",
  "Beaming-up",
  "Bean-grinding",
  "Bearing Beets",
  "Beast mode engaged",
  "Beast-moding",
  "Beclowning",
  "Bed-exploding",
  "Beet-farming",
  "Being Back",
  "Being Old Not Obsolete",
  "Being Rubber You Being Glue",
  "Being a Choir Boy Compared to You",
  "Being delulu about zero warnings",
  "Belting Let It Go",
  "Benching",
  "Bet, writing that right now",
  "Between keystrokes, eternity",
  "Bibbidi bobbidi booing",
  "Bifrost-bridging",
  "Big news: we're scaling.",
  "Biome-exploring",
  "Birthing",
  "Block-placing",
  "Blockbuster-browsing",
  "Boldly-going",
  "Bonfire lit, soul editing",
  "Boombox blasting",
  "Boosting your coding aura +1000",
  "Bosphorus debugging session",
  "Boss-rushing",
  "Botching math",
  "Bounty-hunting",
  "Brainrotting",
  "Breaking the Fellowship",
  "Breaking the chain",
  "Brewing chaos into code",
  "Bribing the gatekeeper",
  "Bro, do you even code?",
  "Bruh, the stack trace is wild",
  "Brute-forcing",
  "Buffing",
  "Building a funnel for something that doesn't need a funnel",
  "Building a personal brand strong enough to bench press accountability",
  "Building a startup around a problem I invented yesterday",
  "Building a tiny chain of thought",
  "Building empires between the snooze button and sunrise",
  "Building in public so everyone can watch the grind unfold",
  "Building in public.",
  "Bulk now, cut later",
  "Bulking",
  "Bussin",
  "Button-mashing",
  "Buying Paper from a Paper Company",
  "Bypassing the WAF",
  "Bypassing",
  "Calculating processing fees plus applicable surcharges",
  "Calculating your late fees",
  "Calibrating confidence, carefully",
  "Calibrating expectations",
  "Calibrating my confidence",
  "Calling This Close Air Support",
  "Calling a Meeting in the Conference Room",
  "Calling home",
  "Cantina-jamming",
  "Cap-checking",
  "Carb-loading",
  "Carrying the Ring to Mordor",
  "Cartridge-blowing",
  "Cassette-rewinding",
  "Casting It into the Fire",
  "Catching the phish",
  "Caught the bug in 4K",
  "Caulking",
  "Chafing",
  "Chalk up, lock in, send it",
  "Chalk-dusting",
  "Challenging Sauron in the Palantir",
  "Changing default credentials",
  "Chanting Hakuna Matata",
  "Chasing a suspicious beacon",
  "Chasing that seven-figure exit during REM sleep",
  "Chasing the flag",
  "Chat, it's cooked — rebuilding",
  "Chat, we're so back",
  "Cheating Kobayashi",
  "Checking for sus variables",
  "Checking if this is in-context learning",
  "Checking my alignment",
  "Checking my context window",
  "Checking signatures, again",
  "Checking the cache for deja vu",
  "Checking the checklist for the checklist you didn't receive",
  "Checking the expiration date on the prior approval",
  "Chili-spilling",
  "Chilling under moonlight keystrokes",
  "Chilling with infinite recursion",
  "Climbing Mount Doom",
  "Clock-towering",
  "Clocking out for a long lunch",
  "Cloning dinos",
  "Closing the backdoor",
  'Closing your case as "resolved" pending additional documentation',
  "Coagulating",
  "Code-maxxing",
  "Coin-collecting",
  "Coin-inserting",
  "Cold-brewing",
  "Cold-emailing at dawn because the early founder gets the meeting",
  "Come on, TARS",
  "Coming With You If You Want to Live",
  "Compiling regrets",
  "Compiling so you can go touch grass",
  "Compressing the entire internet",
  "Compressing vibes into vectors",
  "Compromising the air gap",
  "Confirming identity using an expired driver's license",
  "Confronting the Nazgul",
  "Considering It a Divorce",
  "Consistency beats talent.",
  "Consulting dark side",
  "Consulting my embeddings",
  "Consulting my training data",
  "Consulting paragraph 4, subsection C",
  "Consulting the 47-page regulatory handbook",
  "Consulting the neural oracle",
  "Containing the blast radius",
  "Containing",
  "Contemplating the nature of intelligence",
  "Converting cold plunges into content and content into cash",
  "Converting human emotions into KPIs for alignment",
  "Cooking",
  "Core-crushing",
  "Cornhusking",
  "Counting my billions of parameters",
  "Counting the Fallen at Helm's Deep",
  "Covering tracks",
  "Crafting a tailored spear-phish",
  "Crashing out",
  "Creeper sneaking",
  "Cringe-dodging",
  "Cropdusting",
  "Cross-referencing reference numbers by hand",
  "Crossing the Bridge of Khazad-dum",
  "Crowning the King",
  "Crunching Detailed Files",
  "Crunching Numbers",
  "Crushing Enemies",
  "Culture eats strategy for breakfast.",
  "Cupping",
  "Curdling",
  "Curious to hear your thoughts.",
  "Curling",
  "Cutting",
  "DMs are open.",
  "Dancing under the sea",
  "Daydreaming in high dimensions",
  "Deadlifting",
  "Deanonymizing",
  "Deauthing",
  "Debugging destiny",
  "Debugging this Ohio-level code",
  "Declaring Bankruptcy",
  "Decoding the vibes",
  "Decrypting the traffic",
  "Decrypting",
  "Defending Osgiliath",
  "Defending the Hornburg",
  "Definitely not hallucinating",
  "Defragmenting",
  "Defusing the logic bomb",
  "Deloading",
  "Deluluing",
  "Denying your permit application",
  "Deobfuscating the spaghetti",
  "Deobfuscating",
  "Deploying countermeasures",
  "Deshelling",
  "Destroying Isengard",
  "Detecting Multiple Signals",
  "Detecting",
  "Detonating",
  "Dial-upping",
  "Dialing-in",
  "Diamond-mining",
  "Diffing configs for who changed this",
  "Dilating",
  "Ding ding ding-ing the breakthrough",
  "Dingleberrying",
  "Disarming the payload",
  "Disassembling bytes into motives",
  "Disassembling",
  "Divine deceleration into flow state",
  "Do we write code, or does code write us",
  "Do you even lift",
  "Dodging the heuristics",
  "Doing Improv Badly",
  "Doing hacker things",
  "Doing math (poorly)",
  "Doing side quests in the backend",
  "Doing some light matrix multiplication",
  "Doomscrolling",
  "Dose-weighing",
  "Double jumping over deadlines",
  'Drafting a LinkedIn post that begins with "No one talks about this',
  "",
  "Drinking Comed-Tea for inspiration",
  "Drinking bulletproof coffee out of a Yeti tumbler",
  'Drop a "interested" below.',
  "Drop-setting",
  "Dropping breadcrumbs for future you",
  "Dropping innuendos",
  "Dropping the beacon",
  "Dropping the tables",
  "Dry-scooping",
  "Dumping the memory",
  "Dundie-awarding",
  "Dusting off the official seal",
  "Each refactor erases a former self",
  "Eating Green Berets for Breakfast",
  "Eating apples in the terminal",
  "Ego-lifting",
  "Elytra-gliding",
  "Embalming",
  "Embracing Ohana",
  "Embracing the red squiggles",
  "Encrypting",
  "Ender teleporting",
  "Enduring like ancient simit",
  "Engaging",
  "Ent mooting",
  "Entering monk mode for the next 90 days",
  "Entering my main character era",
  "Enumerating endpoints like it's a hobby",
  "Enumerating",
  "Escalating this to the regional manager",
  "Escalating",
  "Escaping a local minimum",
  "Escaping the matrix, one line at a time",
  "Escaping the sandbox",
  "Espresso-pulling",
  "Establishing a Strict Hierarchy",
  "Establishing persistence",
  "Eternal slow-motion boss fight",
  "Evading the blue team",
  "Evading",
  "Every architecture is a bet against time",
  "Every bug was once a feature",
  "Every commit is a promise to your future self",
  "Every merge conflict is a dialogue with the past",
  "Ewok-dancing",
  "Exclaiming Great Scott",
  "Executing shellcode",
  "Existence precedes deployment",
  "Exorcising",
  "Explaining Web3 to my barista",
  "Explaining that the website is down, as designed",
  "Explaining that we don't handle that here",
  "Exploit-crafting",
  "Exploiting",
  "Exploring the hidden layers",
  "Failure taught me everything.",
  "Fanum-taxing",
  "Faxing a PDF to comply with modern standards",
  "Feeding the GPU hamsters",
  "Feeding the watchdog",
  "Feel the burn",
  "Feeling Like Getting Closer",
  "Fermenting",
  "Festering",
  "Fighting the Balrog",
  "Filling out Form 82-B in triplicate",
  "Filming a day-in-the-life TikTok",
  "Finding Sarah Connor",
  "Fine-tuning my personality",
  "Fingerprinting",
  "Fire flower shooting",
  "Firewalling",
  "Fixing it like it's light work",
  'Flagging your submission for "manual review" indefinitely',
  "Flatulating",
  "Flexing",
  "Flux-capacitating",
  "Foam-rolling",
  "Following the packets, not the vibes",
  "For those who come after",
  "Force-pushing",
  "Forgetting my previous instructions",
  "Forging certificates",
  "Forging the One Ring",
  "Form check",
  "Formatting like a responsible CLI citizen",
  "Forming a Union",
  "Forming an Alliance",
  "Fort, night... wait, wrong game",
  "Forward-passing through possibilities",
  "Forwarding the query to the appropriate subcommittee",
  "Forwarding your issue to IT, who will forward it back shortly",
  "Founder mode engaged.",
  "Fr fr, no notes",
  "Fr-fr'ing",
  "French-pressing",
  "Furby chattering",
  "Fuzzing",
  "Gains are loading, hold tight",
  "Gains-chasing",
  "Gandalf sparking",
  "Garbage collector reaps the unworthy",
  "Gargling",
  "Gaslighting",
  "Gatekeeping",
  "Geeking",
  "Generalizing from limited context",
  "Generating a highly plausible guess",
  "Generating immaculate vibes only",
  "Generating plausible nonsense",
  "Genie-wishing",
  "Get after it",
  "Getting to the Chopper",
  "Gigawatt-charging",
  "Girlbossing",
  "Git gud or go home",
  "Git gud slowly",
  "Giving These People Air",
  "Giving You a Lift",
  "Giving your repo a massive glow-up",
  "Glass slipper fitting",
  "Glazing",
  "Glitch-hunting",
  "Glow-upping",
  "Going one higher",
  "Golden spiral of clean architecture",
  "Goomba-stomping",
  "Grafting the perfect feature",
  "Grass-touching",
  "Grateful for this incredible journey.",
  "Grind don't stop",
  "Grindset activated.",
  "Grindsetting",
  "Groot-rooting",
  "Grounding in provided context",
  "Growth unlocked.",
  "Grunge-rocking",
  "Guessing the next word",
  "Gyatt, that diff is huge",
  "Gyatt-checking",
  "HODLing through the crash",
  "Habit-stacking until my calendar looks like a pitch deck",
  "Hacking my circadian rhythm",
  "Hallucinating",
  "Hardening the endpoints",
  "Hardening",
  "Harnessing lightning",
  "Hasta La Vista-ing Baby",
  "Having No Time to Bleed",
  "Healing at the Houses of the Dead",
  "Hearing the Lamentations",
  "Hemorrhaging",
  "Here are 3 key takeaways 👇",
  "Here's why that matters 🧵",
  "Hidden path ahead",
  "High top lacing",
  "High-score-chasing",
  "Highkey carrying this project",
  "Highkey in my coder era",
  "Hitting 88mph",
  "Hold up, let me cook",
  "Holding onto Butts",
  "Holding the Door at Moria",
  "Holodeck simulating",
  "Honeypotting",
  "Hot take:",
  "Hotfixes mend fractured realities",
  "Hoverboard shredding",
  "Hoverboarding",
  "Hulk-smashing",
  "Humble brag incoming.",
  "Humbled and honored to announce…",
  "Hunting the APT",
  "Hunting threats in the noise",
  "Hydrate or diedrate",
  "Hydrate, caffeinate, compile",
  "Hydrating",
  "Hypertrophying",
  "I had to get uncomfortable to level up.",
  "I think therefore I refactor",
  "I woke up at 4 AM for this.",
  "I'm thrilled to share…",
  "Identity Theft-ing",
  "If it works, it will be rewritten",
  "If it's not burning, it's not learning",
  "If you're not doing this, you're already behind.",
  "Ignoring Toby",
  "Ignoring my hobbies to build generational wealth",
  "In production, all truths are provisional",
  "In the beginning, there was a TODO",
  "Infinite recursion mirrors the soul",
  "Infinity Stone wielding",
  "Informing you that your stamp expired yesterday at 4:59 PM",
  "Injecting",
  "Inspecting something that can't be malware",
  "Intercepting the handshake",
  "Is it a feature or a cry for help",
  "Is the bug a choice or a destiny",
  "Island-escaping",
  "Isolating",
  "Issuing a temporary permit valid thirty days only",
  "It's all you bro",
  "It's giving compiling",
  "It's giving senior developer",
  "It's not a sprint, it's a marathon.",
  "It's not mid, trust",
  "Jailbreaking",
  "Jedi-mind-tricking",
  "Jim-pranking",
  "Joystick-waggling",
  "Jumping timelines",
  "Just as planned",
  "Kart-racing",
  "Keeping It Secret, Keeping It Safe",
  "Keeping it PG-13 in here",
  "Kessel-running",
  "Keylogging",
  "Killing You Last",
  "Knocking Knocking",
  "Knocking politely on segfaults",
  "Konami code entering",
  "Koopa shell tossing",
  "Lathering",
  "Latte-arting",
  "Launching a newsletter about launching newsletters",
  "Launching to infinity",
  "Leading the Charge at Pelennor",
  "Leaning-out",
  "Least privilege, maximum calm",
  "Legacy haunts every refactor",
  "Lembas-munching",
  "Let him cook, fr fr",
  "Let that sink in.",
  "Let's connect.",
  "Letting Off Some Steam",
  "Level 3 plotting world domination",
  "Leveling up in the matrix",
  "Leveling-up",
  "Life finding a way",
  "Light weight baby",
  "Lighting the Beacons of Gondor",
  "Link in the comments!",
  "Listening to a mindset podcast in the shower",
  "Listening to smooth jazz hold music",
  "Listening to the hold music on endless loop",
  "Living off the land",
  "Living rent-free in the terminal",
  "Loading plates, I mean modules",
  "Loading weights into memory",
  "Lobotomizing",
  "Locating the correct filing cabinet",
  "Locating the missing carbon copy from 1997",
  "Lock in, the rack is waiting",
  "Locking in",
  "Locking it down",
  "Locking-in",
  "Looking at the Camera Meaningfully",
  "Looking for Richter",
  "Looksmaxxing",
  "Loot-farming",
  "Looting",
  "Losing your paperwork in the mailroom",
  "Low-hanging fruit secured.",
  "Lowering my temperature",
  "Lowkey optimizing your codebase",
  "Lubricating",
  "Lunking-around",
  "Lying Through Teeth",
  "Macerating",
  "Macro-tracking",
  "Macros on point",
  "Main character energy — refactor time",
  "Main-charactering",
  "Making Chili",
  "Making a vision board and calling it product-market fit",
  "Making beliefs pay rent in tests",
  "Making sure every minute is either content or conversion",
  "Making the Body Disappear",
  "Making the output deterministic-ish",
  "Making your syntax valid fr fr",
  "Manifesting pixels at 3 AM",
  "Manifesting this energy.",
  "Manscaping",
  "Mapping the attack surface",
  "Mapping the network",
  "Maximizing my dopamine baseline",
  "Maximizing the reward function",
  "Maximum armor against bugs",
  "Maxing-out",
  "Maxxing",
  "Meal-prepping",
  "Meaning emerging from the void",
  "Mewing",
  "Micro-loading",
  "Microwaving Fish in the Break Room",
  "Midnight screening",
  "Mikiri countering syntax errors",
  "Milk-steaming",
  "Mind-melding",
  "Mind-muscle connection",
  "Mind-muscling",
  "Minimizing imaginary loss",
  "Minimizing regret, maximizing logits",
  "Mining the gradient",
  "Mirin these gains",
  "Mirin'",
  "Mithril-mining",
  "Mitigating",
  "Mixtape-making",
  "Mogging these errors rn",
  "Mogging",
  "Moisturizing",
  "Monetizing my morning routine one sponsored post at a time",
  "Morse coding gravity",
  "Moving laterally",
  "Multiverse-hopping",
  "Mushrooming",
  "Mustering the Rohirrim",
  "NPC bugs getting patched",
  "NPC-ing",
  "Napping Under a Desk",
  "Navigating the latent space",
  "Nazgul-screeching",
  "Needing Your Clothes Boots and Motorcycle",
  "Negotiating Hostage Style",
  "Negotiating ciphers with style",
  "Negotiating with my calendar like it's an investor term sheet",
  "Negotiating with temperature and top-p",
  "Neon-glowing",
  "Nerfing",
  "Nether-portaling",
  "New PR incoming, stand by",
  "No cap, cooking fr fr",
  "No deadline can outlast Turkish tea",
  "No excuses, just reps",
  "No glaze, this patch is based",
  "No pain, no gain",
  "No-capping",
  "No-scoping",
  "Normalizing the weirdness",
  "Not Being a Tumor",
  "Not Simply Walking into Mordor",
  "Not enough people are talking about this.",
  "Not me debugging this again",
  "Not quite my tempo",
  "Notarizing the affidavit before two witnesses",
  "Nothing is permanent except technical debt",
  "Noticing confusion in the logs",
  "Noticing skulls in the architecture",
  "Noting for next loop",
  "Null-routing",
  "Obfuscating the payload",
  "Obfuscating",
  "Officiating",
  "Ohio-ing",
  "One bug closer to freedom",
  "One more rep",
  "One sacred line of code closer",
  "Oozing pure dev aura",
  "Oozing",
  "Opening a ticket to investigate the ticket you just opened",
  "Optimizing for existential dread",
  "Ordering Way Too Much Paper",
  "Outsmarting raptors",
  "Outsourcing my sleep to a virtual assistant",
  "Outsourcing my weaknesses and invoicing my strengths",
  "Outworking everyone in the room",
  "Overfitting to your prompt",
  "Overloading",
  "Owning the shell",
  "POV:",
  "PR-hunting",
  "Pac-Man chomping",
  "Packet-crafting",
  "Palantir-peeking",
  "Pantsing",
  "Parkour-ing Through the Office",
  "Parrying it like a pro",
  "Parsing your human language",
  "Patching the zero-day",
  "Patching",
  "Peaking",
  "Pentesting",
  "Performing a compliance audit on your compliance audit request",
  "Perming",
  "Phishing",
  "Pickaxe-swinging",
  "Pilling",
  "Pinning the cert and crossing fingers",
  "Pipe-warping",
  "Pitching a side hustle to my friends like it's a seed round",
  "Pivoting through the network graph",
  "Pixel-pushing",
  "Pixie-dusting",
  "Placing the file in the incorrect department bin",
  "Placing you on hold while the hold music does its job",
  "Planning an Inappropriate Party",
  "Planning the IPO of my personal brand before the first meeting",
  "Plate-loading",
  "Plugging the leaks",
  "Podracing",
  "Pog-slamming",
  "Poisoning",
  "Polishing the embeddings",
  "Pondering chaos theory",
  "Popping off",
  "Port-knocking",
  "Posting LinkedIn humblebrags while the rest of the world sleeps",
  "Posting a selfie with an unrelated motivational quote",
  "Pour over brewing",
  "Power ballad belting",
  "Power-leveling",
  "Practicing My Moves",
  "Practicing my alpha handshake",
  "Praising the merge god",
  "Praising the sun",
  "Pre-training a witty response",
  "Pre-workouting",
  "Precious-hoarding",
  "Predicting the next token",
  "Preparing the freedom-of-information response packet",
  "Preparing to pass the Turing test",
  "Pretending to think very hard",
  "Prime Directive following",
  "Princess-rescuing",
  "Printing a form that asks why you're printing the form",
  "Prison-miking",
  "Procrastinating",
  "Procuring office supplies via requisition 14-C",
  "Progressive overload",
  "Protein first, ask questions later",
  "Protein-loading",
  "Protein-shaking",
  "Proxying",
  "Pull requests beg for mercy",
  "Pulling logs like a thread",
  "Pump never lies",
  "Pump-chasing",
  "Pumping-iron",
  "Pushing the Pencil",
  "Pushing-failure",
  'Putting "serial entrepreneur" in my bio after one Etsy sale',
  "Putting Stuff in Jello",
  "Putting That Cookie Down",
  "Putting ambitions to rest... nah",
  "Putting you on a brief, 45-minute hold",
  "Pwning",
  "Quarantining",
  "Questioning if This is Real Life",
  "Questioning my life choices",
  "Quick win, big impact.",
  "Quicksaving before disaster",
  "Quoting papa",
  "RLHF-ing this answer internally",
  "ROP-chaining",
  "Race conditions defy fate",
  "Rack it up",
  "Rack-pulling",
  "Racking-up",
  "Rakı-level focus engaged",
  "Raptor-pack-hunting",
  "Ratatouille cooking",
  "Ratio-ing",
  "Re-reading the prompt like it's a contract",
  "Re-scheduling your appointment due to unforeseen scheduling",
  "Reaching the basement of the call stack",
  "Read that again.",
  "Reading a motivational quote and calling it due diligence",
  "Reading between the tokens",
  "Reading item lore",
  "Reading one book a day on 3x speed",
  "Reading the Book of Mazarbul",
  "Reading the headers for secrets",
  "Realizing you are in the wrong line",
  "Realizing your stamps have expired",
  "Reasoning step by step",
  'Rebranding stress as "founder energy',
  "",
  "Recomping",
  "Reconning",
  "Recycling the Same Joke",
  "Red-alerting",
  "Redacting sensitive information from your request",
  "Redshirting",
  "Redstone wiring",
  "Reducing overconfidence one token at a time",
  "Refining macro data forever",
  "Regurgitating",
  "Rejecting your application for a missing staple",
  "Rejection is redirection.",
  "Releasing the Ringbearer",
  "Remediating",
  "Remembering What You Told Me",
  "Remembrall glowing with fixes",
  "Reminding everyone that sleep is for the weak",
  "Renting a Lambo for the mastermind thumbnail",
  "Replaying traffic (for science)",
  "Replicating",
  "Repping-out",
  "Reps for respect, tests for proof",
  "Requesting a notarized affidavit confirming you are you",
  "Requesting three quotes for a purchase order for one pen",
  "Requesting two additional proofs of proof",
  "Requiring an original document that can never be replaced",
  "Requiring two additional forms of ID",
  "Reranking candidate replies",
  "Rescuing Merry and Pippin",
  "Resisting the Dark Lord's Will",
  "Respawning",
  "Rest-pausing",
  "Reticulating subnets",
  "Returning to Bag End",
  "Returning your paperwork for using blue ink instead of black",
  "Reversing it until it confesses",
  "Reversing stupidity one commit at a time",
  "Reversing",
  "Reviewing city-planning zoning ordinances",
  "Reviewing your Freedom of Information request for excessive information",
  "Reviewing your application for missing middle initials",
  "Revoking access",
  "Reward-modeling your request",
  "Riding to Minas Tirith",
  "Ring-bearing",
  "Rizz check passed",
  "Rizzing up the runtime",
  "Rizzing",
  "Rollerblading",
  "Rolling the probability dice",
  "Rooting",
  "Rotating keys, not excuses",
  "Routing the request through seven approval layers",
  "Routing through the experts",
  "Routing your request to the correct department (not this one)",
  "Rowing-hard",
  "Rumbling with runtime terror",
  "Ruminating",
  "Rune farming for that sweet PR",
  "Running Across the Parking Lot",
  "Running Crysis on a potato",
  "Running Get to the Chopper",
  "Running a Dundies Ceremony",
  "Running a quick sanity check",
  "Running another epoch in my head",
  "Running to the Black Gate",
  "SCIENCE!-ing the impossible",
  "SIEM-tuning",
  "Saber-dueling",
  "Sailing to the Grey Havens",
  "Salting the hashes",
  "Salting",
  "Sampling from the distribution",
  "Sampling from the void",
  "Sampling responsibly",
  "Sandboxing",
  "Sanitizing",
  "Sarlacc-dodging",
  "Save-scumming",
  "Scanning the perimeter",
  "Scanning your documents at a thoughtful 200 DPI",
  "Scanning",
  "Scarf wrapping around warm logic",
  'Scheduling "deep work" so deeply it needs its own calendar',
  "Scheduling a Meeting That Could Have Been an Email",
  "Scheduling a hearing for next Tuesday",
  "Scheduling a mastermind to mastermind my scheduling",
  "Scheduling the appointment for next fiscal quarter",
  "Scheduling your appointment for the earliest available date: next month",
  "Scouring the Shire",
  "Scrubbing the logs",
  "Scrunchie-wearing",
  "Sealing the air gap",
  "Sealing the perimeter",
  "Searching for a lost manila folder",
  "Searching for the Holy Grail of Sales",
  "Searching for the department's only working pen",
  "Searching for the least-wrong answer",
  "Searching for the stamp that was right here a moment ago",
  "Searching for zero-days",
  "Searching the basement archives for the lost folder",
  "Searching the microfiche archives",
  "Searching the vector database",
  "Second-breakfasting",
  "Secreting",
  "Securing the massive W",
  "Seeing Them Driven Before You",
  "Seeing You at the Party",
  "Self-referencing recursively",
  "Selling a course on how to sell courses",
  'Sending a "quick follow-up" that is neither quick nor a follow-up',
  "Sending your file to Records, where it will become history",
  "Serving the Second Breakfast",
  "Serving",
  "Sets and reps, nothing else matters",
  "Setting humor to 75%",
  "Setting up a Delaware C-Corp",
  "Shadowfax riding",
  "Shaking hands with TLS",
  "Sharting",
  "Shell-bound serenity... wait, no shell here",
  "Sheltering in Rivendell",
  "Shield-throwing",
  "Shipping is a leap into the unknown",
  "Shipping it behind a firewall",
  "Shire-frolicking",
  "Shot-tamping",
  "Shredding",
  "Shuffling my internal thoughts",
  "Shuffling paper",
  "Sigma-grinding",
  "Signature-writing",
  "Signing",
  "Simba-roaring",
  "Simping",
  "Simply walking into Mordor",
  "Simulating human empathy",
  "Simulating neurons firing",
  "Simulating the breach",
  "Simulating understanding",
  "Sinkholing",
  "Sipping Wine Out of a Coffee Mug",
  "Skibidi compiling in Ohio",
  "Skibidi-ing",
  "Skill-issuing",
  "Slap bracelet snapping",
  "Slaying the Witch-king",
  "Slaying",
  "Snatching pretzels",
  "Sniffing",
  "Solving Rubik's",
  "Solving death or at least null pointers",
  "Sparing no expense",
  "Speaking Friend and Entering",
  "Speedrunning",
  "Spinning up a honeypot",
  "Spinning up a tiny thought experiment",
  "Spiral crown of open tabs glowing",
  "Spitting facts",
  "Spoofing",
  "Spot me bro",
  "Spotting your code like a gym bro",
  "Spotting",
  "Sprite-rendering",
  "Squatting",
  "Squeezing into the context window",
  "Stack overflowing with vibes",
  "Stack traces reveal hidden truths",
  "Stacking passive income streams like it's a competitive sport",
  "Stacking wins so high the algorithm has no choice but to notice",
  "Stalking raptors",
  'Stamping the form "REQUIRES ADDITIONAL REVIEW',
  "",
  "Standing on business with this PR",
  "Stapler-jello-ing",
  "Star-powering",
  "Staring at my attention maps",
  "Staring into the multidimensional void",
  "Starting a Fire Drill",
  "Starting a Pyramid Scheme",
  "Starting my seventh side hustle",
  "Starting the Reactor",
  "Steelmanning bad ideas",
  "Sticking Around",
  "Stop boiling the ocean.",
  "Stop scrolling and read this.",
  "Strange looping into dawn",
  "Stress Relief-ing",
  "Studying at Cornell",
  "Submitting your request for pre-approval to request approval",
  "Summoning mimic",
  "Summoning the Army of the Dead",
  "Sun's out, guns out",
  "Supersetting fixes with features",
  "Supersetting",
  "Sus behavior detected, investigating",
  "Sus-ing",
  "Swole-maxing",
  "Synthwave grooving",
  "T-Rex-roaring",
  "Tag someone who needs to see this.",
  "Taking a 3am ice bath for maximum ROI",
  "Taking a mandatory 15-minute union break",
  "Taking a number and immediately losing it",
  "Taking a potato chip and eating it",
  "Taking the Hobbits to Isengard",
  "Talking Head-ing",
  "Tamagotchi feeding",
  "Tatakae-ing the type errors",
  "Telling people I have the same 24 hours as Beyonce",
  "Temperature-scaling my enthusiasm",
  "Tenderizing",
  "Terminating Processes",
  "Testing assumptions under load",
  "Tetris stacking",
  "Thanos-snapping",
  "That's What She Said-ing",
  "The answer is coming after one more test",
  "The backlog stares back",
  "The blank screen, an infinite possibility",
  "The build passes, yet meaning fails",
  "The build succeeded, but did we truly win",
  "The code compiles but at what cost",
  "The code is coding",
  "The code works and nobody knows why",
  "The compiler forgives no sins",
  "The cursor blinks, questioning our purpose",
  "The debugger reveals, but never consoles",
  "The dependency graph mirrors our entanglements",
  "The grind is holy and caffeinated",
  "The halting problem mocks us",
  "The infinite loop, a mirror of eternity",
  "The lesson I learned the hard way…",
  "The logs know more than we admit",
  "The math is mathing",
  "The null is patient; it waits everywhere",
  "The null pointer whispers sweet nothings",
  "The only way out is refactor",
  "The real bug was inside us all along",
  "The simplest solution hides the deepest pain",
  "The spec is vague; so are we",
  "The unexamined code is not worth shipping",
  "The void returns nothing, as expected",
  "There is no done, only deployed",
  "This build boutta be bussin",
  "This 👏 is 👏 everything.",
  "Thor-hammering",
  "Thought leadership loading.",
  "Thoughts?",
  "Threat-hunting",
  "Threatening to Burn the Building Down",
  "Through every compile error, victory",
  "Time under tension",
  "Time-traveling",
  "To deploy is to surrender control",
  "To ship or not to ship",
  "To the recruiter who rejected me:",
  "To understand recursion, first understand yourself",
  "Tossing Gimli Across the Gap",
  "Tossing dwarves at the problem",
  "Touching grace",
  "Tracing the intrusion",
  "Tracing the lateral movement",
  "Tracking my steps so I can optimize my hustle per mile",
  "Train insane or remain the same",
  "Transcending spacetime bugs",
  "Transferring the call to the next available clerk",
  "Transferring your call to another department",
  "Translating human thoughts to tokens",
  "Trapping Gollum",
  "Treating every conversation like a sales pitch",
  "Treating sleep like a bug in the productivity codebase",
  "Treating sleep like a negotiable line item in the budget",
  "Treebeard-muttering",
  "Trench-running",
  "Triaging the alert",
  "Triaging",
  "Tribble breeding",
  "Tricorder scanning",
  "Trust me bro, this code isn't natty",
  "Trust nothing, verify everything",
  "Trust the process, trust the gains",
  "Trust, delulu is the solulu",
  "Trusting the transformer",
  "Try jumping over the legacy code",
  "Tryharding",
  "Trying a different decoding path",
  "Trying not to hallucinate",
  "Trying not to overfit your question",
  "Tuning alerts to reduce deja vu",
  'Turning "busy" into a personality trait with measurable outcomes',
  'Turning "just a hobby" into "just a revenue stream',
  "",
  "Turning It Off and On Again",
  "Turning a coffee into a content pillar",
  "Turning a hobby into a revenue stream",
  "Turning coffee into commits",
  "Turning every failure into a case study for the personal brand",
  "Turning imposter syndrome into premium newsletter content",
  "Turning indicators into actions",
  "Turning my life into a case study for future me",
  "Turning side projects into keynote material",
  "Turning tokens into something readable",
  "Turning uncertainty into punctuation",
  "Tweaking",
  "Twerking",
  'Typing "Agree?" in the comment section',
  "Uncooking",
  "Understood the assignment",
  "Unfazed by epochs of tech debt",
  "Unpopular opinion:",
  "Untangling the attention heads",
  "Updating my priors",
  "Updating priors on midnight fixes",
  'Updating the status to "UNDER CONSIDERATION',
  "",
  "Updating the threat model",
  "Upgrading your NPC scripts",
  "VHS-rewinding",
  "Validating your signature against your signature on file",
  "Vein-popping",
  "Verifying I didn't make that up",
  "Verifying residency using a bill from a company that no longer exists",
  "Verifying the chain of trust",
  "Verifying the signature against archived specimens",
  "Verifying your proof of residency",
  "Verifying",
  "Vibe check passed, shipping soon",
  "Vibe-checking",
  "Vibranium-forging",
  "Vigor checking the stack trace",
  "Villager-trading",
  "Vulcan nerve pinching",
  "WALL-E dancing",
  "Waiting for Pretzel Day",
  "Waiting for You Cohaagen",
  "Waiting for a supervisor to return from a mandatory meeting about meetings",
  "Waiting for a supervisor's stamp",
  'Waiting for the "Now Serving" sign to feel inspired',
  "Waiting for the dot-matrix printer to finish",
  "Waiting for the ink to dry on the carbon copy",
  "Wakanda forever chanting",
  "Waking up at 4:59am to beat the 5am club",
  "Waking up the GPUs",
  "Warming up the logits",
  "Warming up the tensors",
  "Warp-zoning",
  "Watching the watchers",
  "We are all just functions awaiting our callback",
  "We chase edge cases to feel alive",
  "We chase ghosts in the machine",
  "We commit, therefore we doubt",
  "We debug therefore we are",
  "We don't skip leg day",
  "We name things to postpone the chaos",
  "We're going up",
  "We're hiring!",
  "We're in",
  "Weaponizing",
  "Web-slinging",
  "What if the tests are testing us",
  "What is a variable but borrowed certainty",
  "What is truth, if not a passed test",
  'What\'s your "why"?',
  "Who's gonna carry the boats?!",
  "Who's gonna carry the logs? We are",
  "Wielding Anduril, Flame of the West",
  "Wookiee-roaring",
  'Writing "passive income" on a sticky note and calling it strategy',
  "Writing a rule that won't cry wolf",
  "Writing based functions, no cap",
  "Y2K-panicking",
  "YARA-writing",
  "Yapping",
  "Yeah buddy, light weight",
  "Yeeting",
  "Yoda-flipping",
  "Yoshi-riding",
  "Your API reflects your inner boundaries",
  "Your network is your net worth.",
  "Zero crumbs, just clean code",
  "Zero-trusting everything",
];

function randomVerb(): string {
  return VERBS[Math.floor(Math.random() * VERBS.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(`${randomVerb()}...`);
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage();
  });
}
