/**
 * Spinner Verbs Extension
 *
 * Replaces the default working message with a random fun verb
 * on each turn. A mix of The Office, Lord of the Rings,
 * Arnold Schwarzenegger, and Predator references.
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const VERBS = [
	"Assistant Regional Managing",
	"Attending Sensitivity Training",
	"Awakening the Ents",
	"Bearing Beets",
	"Beclowning",
	"Being Back",
	"Being Old Not Obsolete",
	"Being Rubber You Being Glue",
	"Being a Choir Boy Compared to You",
	"Birthing",
	"Breaking the Fellowship",
	"Buying Paper from a Paper Company",
	"Calling This Close Air Support",
	"Calling a Meeting in the Conference Room",
	"Carrying the Ring to Mordor",
	"Casting It into the Fire",
	"Caulking",
	"Chafing",
	"Challenging Sauron in the Palantir",
	"Climbing Mount Doom",
	"Coagulating",
	"Coming With You If You Want to Live",
	"Confronting the Nazgul",
	"Considering It a Divorce",
	"Cornhusking",
	"Counting the Fallen at Helm's Deep",
	"Cropdusting",
	"Crossing the Bridge of Khazad-dum",
	"Crowning the King",
	"Crunching Detailed Files",
	"Crunching Numbers",
	"Crushing Enemies",
	"Curdling",
	"Declaring Bankruptcy",
	"Defending Osgiliath",
	"Defending the Hornburg",
	"Defragmenting",
	"Deshelling",
	"Destroying Isengard",
	"Detecting Multiple Signals",
	"Dilating",
	"Dillon You Son of a Bitching",
	"Dingleberrying",
	"Doing Improv Badly",
	"Eating Green Berets for Breakfast",
	"Embalming",
	"Establishing a Strict Hierarchy",
	"Exorcising",
	"Feeling Like Getting Closer",
	"Fermenting",
	"Festering",
	"Fighting the Balrog",
	"Finding Sarah Connor",
	"Flatulating",
	"Forging the One Ring",
	"Forming a Union",
	"Forming an Alliance",
	"Gargling",
	"Getting to the Chopper",
	"Giving These People Air",
	"Giving You a Lift",
	"Hallucinating",
	"Hasta La Vista-ing Baby",
	"Having No Time to Bleed",
	"Healing at the Houses of the Dead",
	"Hearing the Lamentations",
	"Hemorrhaging",
	"Holding onto Butts",
	"Holding the Door at Moria",
	"Hydrating",
	"Identity Theft-ing",
	"Ignoring Toby",
	"Keeping It Secret, Keeping It Safe",
	"Killing You Last",
	"Knocking Knocking",
	"Lathering",
	"Leading the Charge at Pelennor",
	"Letting Off Some Steam",
	"Lighting the Beacons of Gondor",
	"Lobotomizing",
	"Looking at the Camera Meaningfully",
	"Looking for Richter",
	"Lubricating",
	"Lying Through Teeth",
	"Macerating",
	"Making Chili",
	"Making You One Ugly Motherfucker",
	"Making the Body Disappear",
	"Manscaping",
	"Microwaving Fish in the Break Room",
	"Moisturizing",
	"Mustering the Rohirrim",
	"Napping Under a Desk",
	"Needing Your Clothes Boots and Motorcycle",
	"Negotiating Hostage Style",
	"Not Being a Tumor",
	"Not Simply Walking into Mordor",
	"Officiating",
	"Oozing",
	"Ordering Way Too Much Paper",
	"Pantsing",
	"Parkour-ing Through the Office",
	"Planning an Inappropriate Party",
	"Practicing My Moves",
	"Procrastinating",
	"Pushing the Pencil",
	"Putting Stuff in Jello",
	"Putting That Cookie Down",
	"Questioning if This is Real Life",
	"Reading the Book of Mazarbul",
	"Recycling the Same Joke",
	"Regurgitating",
	"Releasing the Ringbearer",
	"Remembering What You Told Me",
	"Rescuing Merry and Pippin",
	"Resisting the Dark Lord's Will",
	"Returning to Bag End",
	"Riding to Minas Tirith",
	"Ruminating",
	"Running Across the Parking Lot",
	"Running Get to the Chopper",
	"Running a Dundies Ceremony",
	"Running to the Black Gate",
	"Sailing to the Grey Havens",
	"Scheduling a Meeting That Could Have Been an Email",
	"Scouring the Shire",
	"Searching for the Holy Grail of Sales",
	"Secreting",
	"Seeing Them Driven Before You",
	"Seeing You at the Party",
	"Serving the Second Breakfast",
	"Sharting",
	"Sheltering in Rivendell",
	"Sipping Wine Out of a Coffee Mug",
	"Slaying the Witch-king",
	"Speaking Friend and Entering",
	"Starting a Fire Drill",
	"Starting a Pyramid Scheme",
	"Starting the Reactor",
	"Sticking Around",
	"Stress Relief-ing",
	"Studying at Cornell",
	"Summoning the Army of the Dead",
	"Taking the Hobbits to Isengard",
	"Talking Head-ing",
	"Tenderizing",
	"Terminating Processes",
	"That's What She Said-ing",
	"Threatening to Burn the Building Down",
	"Tossing Gimli Across the Gap",
	"Trapping Gollum",
	"Turning It Off and On Again",
	"Turning You Into a Goddamn Sexual Tyrannosaurus",
	"Twerking",
	"Waiting for Pretzel Day",
	"Waiting for You Cohaagen",
	"Wielding Anduril, Flame of the West",
	"Yeeting",
];

function randomVerb(): string {
	return VERBS[Math.floor(Math.random() * VERBS.length)];
}

export default function (pi: ExtensionAPI) {
	pi.on("turn_start", async (_event, ctx) => {
		ctx.ui.setWorkingMessage(`${randomVerb()}...`);
	});

	pi.on("turn_end", async (_event, ctx) => {
		ctx.ui.setWorkingMessage();
	});
}
