# extracted from 1323952.png; tuned for readable terminal colors
mode = "dark"
accent = "#a0a5da"
cursor = "#a0a5da"
foreground = "#e0def0"
background = "#203755"
selection_foreground = "#203755"
selection_background = "#a0a5da"

color0 = "#2f4465"
color1 = "#d49191"
color2 = "#91d491"
color3 = "#d0cab2"
color4 = "#a0a5da"
color5 = "#d7b0db"
color6 = "#8bc6d0"
color7 = "#c3c5d9"
color8 = "#8190aa"
color9 = "#deaeae"
color10 = "#aedeae"
color11 = "#dbd7c6"
color12 = "#b9bce2"
color13 = "#e0c5e3"
color14 = "#ade0e8"
color15 = "#e0def0"
