accent = "#d9a56c"
cursor = "#f0eaed"
foreground = "#f0eaed"
background = "#0d0509"
selection_foreground = "#0d0509"
selection_background = "#f0eaed"

color0 = "#0d0509"
color1 = "#e85f6f"
color2 = "#f29b9a"
color3 = "#d4a882"
color4 = "#d9a56c"
color5 = "#d1b399"
color6 = "#e8c099"
color7 = "#f0eaed"
color8 = "#4a3c45"
color9 = "#ff7a8a"
color10 = "#ffb5b4"
color11 = "#e6ba94"
color12 = "#ebb97e"
color13 = "#e3c5ab"
color14 = "#fbd2ab"
color15 = "#ffffff"
