background = #0d0509
foreground = #f0eaed
cursor-color = #f0eaed
selection-background = #f0eaed
selection-foreground = #0d0509

palette = 0=#0d0509
palette = 1=#e85f6f
palette = 2=#f29b9a
palette = 3=#d4a882
palette = 4=#d9a56c
palette = 5=#d1b399
palette = 6=#e8c099
palette = 7=#f0eaed
palette = 8=#4a3c45
palette = 9=#ff7a8a
palette = 10=#ffb5b4
palette = 11=#e6ba94
palette = 12=#ebb97e
palette = 13=#e3c5ab
palette = 14=#fbd2ab
palette = 15=#ffffff

macos-icon = custom-style
macos-icon-ghost-color = #d9a56c
macos-icon-screen-color = #0d0509
