accent = "#BB9AF7"
cursor = "#814DDE"
foreground = "#FFFFFF"
background = "#05010C"
selection_foreground = "#05010C"
selection_background = "#FFFFFF"

color0 = "#382952"
color1 = "#F07178"
color2 = "#C2B8FF"
color3 = "#DDCCFF"
color4 = "#BB9AF7"
color5 = "#B49AE6"
color6 = "#A6B8FF"
color7 = "#DECCFF"
color8 = "#6B578F"
color9 = "#FF8A95"
color10 = "#B3A8F7"
color11 = "#D1BFF7"
color12 = "#CBA6F8"
color13 = "#C4AAF0"
color14 = "#C2CCFF"
color15 = "#C3AAF0"
