mode = "dark"

accent = "#bb9af7"
selection = "#141029"
muted = "#6b578f"

background = "#05010c"
dark_background = "#040109"
darker_background = "#030108"
lighter_background = "#141029"

foreground = "#ffffff"
dark_foreground = "#deccff"
light_foreground = "#ffffff"
bright_foreground = "#c3aaf0"

red = "#f07178"
yellow = "#ddccff"
orange = "#f07178"
green = "#c2b8ff"
cyan = "#a6b8ff"
blue = "#bb9af7"
magenta = "#b49ae6"
brown = "#814dde"

bright_red = "#ff8a95"
bright_yellow = "#d1bff7"
bright_green = "#b3a8f7"
bright_cyan = "#c2ccff"
bright_blue = "#cba6f8"
bright_magenta = "#c4aaf0"

cursor = "#814dde"
selection_foreground = "#05010c"
selection_background = "#ffffff"

color0 = "#382952"
color1 = "#f07178"
color2 = "#c2b8ff"
color3 = "#ddccff"
color4 = "#bb9af7"
color5 = "#b49ae6"
color6 = "#a6b8ff"
color7 = "#deccff"
color8 = "#6b578f"
color9 = "#ff8a95"
color10 = "#b3a8f7"
color11 = "#d1bff7"
color12 = "#cba6f8"
color13 = "#c4aaf0"
color14 = "#c2ccff"
color15 = "#c3aaf0"
