background = #05010C
foreground = #FFFFFF
cursor-color = #814DDE
selection-background = #FFFFFF
selection-foreground = #05010C

palette = 0=#382952
palette = 1=#F07178
palette = 2=#C2B8FF
palette = 3=#DDCCFF
palette = 4=#BB9AF7
palette = 5=#B49AE6
palette = 6=#A6B8FF
palette = 7=#DECCFF
palette = 8=#6B578F
palette = 9=#FF8A95
palette = 10=#B3A8F7
palette = 11=#D1BFF7
palette = 12=#CBA6F8
palette = 13=#C4AAF0
palette = 14=#C2CCFF
palette = 15=#C3AAF0

macos-icon = custom-style
macos-icon-ghost-color = #BB9AF7
macos-icon-screen-color = #05010C
