#!/usr/bin/env bash
# Catppuccin Mocha — tmux @thm_* palette

tmux set -g @thm_bg "#24273a"
tmux set -g @thm_fg "#cad3f5"
tmux set -g @thm_rosewater "#f4dbd6"
tmux set -g @thm_flamingo "#f0c6c6"
tmux set -g @thm_pink "#f5bde6"
tmux set -g @thm_mauve "#c6a0f6"
tmux set -g @thm_red "#ed8796"
tmux set -g @thm_maroon "#ee99a0"
tmux set -g @thm_peach "#f5a97f"
tmux set -g @thm_yellow "#eed49f"
tmux set -g @thm_green "#a6da95"
tmux set -g @thm_teal "#8bd5ca"
tmux set -g @thm_sky "#91d7e3"
tmux set -g @thm_sapphire "#7dc4e4"
tmux set -g @thm_blue "#8aadf4"
tmux set -g @thm_lavender "#b7bdf8"
tmux set -g @thm_subtext_1 "#b8c0e0"
tmux set -g @thm_subtext_0 "#a5adcb"
tmux set -g @thm_overlay_2 "#939ab7"
tmux set -g @thm_overlay_1 "#8087a2"
tmux set -g @thm_overlay_0 "#6e738d"
tmux set -g @thm_surface_2 "#5b6078"
tmux set -g @thm_surface_1 "#494d64"
tmux set -g @thm_surface_0 "#363a4f"
tmux set -g @thm_mantle "#1e2030"
tmux set -g @thm_crust "#181926"
