#!/usr/bin/env bash
# Catppuccin Latte — tmux @thm_* palette

tmux set -g @thm_bg "#eff1f5"
tmux set -g @thm_fg "#4c4f69"
tmux set -g @thm_rosewater "#dc8a78"
tmux set -g @thm_flamingo "#dd7878"
tmux set -g @thm_pink "#ea76cb"
tmux set -g @thm_mauve "#8839ef"
tmux set -g @thm_red "#d20f39"
tmux set -g @thm_maroon "#e64553"
tmux set -g @thm_peach "#fe640b"
tmux set -g @thm_yellow "#df8e1d"
tmux set -g @thm_green "#40a02b"
tmux set -g @thm_teal "#179299"
tmux set -g @thm_sky "#04a5e5"
tmux set -g @thm_sapphire "#209fb5"
tmux set -g @thm_blue "#1e66f5"
tmux set -g @thm_lavender "#7287fd"
tmux set -g @thm_subtext_1 "#5c5f77"
tmux set -g @thm_subtext_0 "#6c6f85"
tmux set -g @thm_overlay_2 "#7c7f93"
tmux set -g @thm_overlay_1 "#8c8fa1"
tmux set -g @thm_overlay_0 "#9ca0b0"
tmux set -g @thm_surface_2 "#acb0be"
tmux set -g @thm_surface_1 "#bcc0cc"
tmux set -g @thm_surface_0 "#ccd0da"
tmux set -g @thm_mantle "#e6e9ef"
tmux set -g @thm_crust "#dce0e8"
