mode = "dark"

accent = "#8d8d8d"
selection = "#1a1a1a"
muted = "#7a7a7a"

background = "#000000"
dark_background = "#090909"
darker_background = "#070707"
lighter_background = "#1a1a1a"

foreground = "#ffffff"
dark_foreground = "#505050"
light_foreground = "#ececec"
bright_foreground = "#ffffff"

red = "#a4a4a4"
yellow = "#cecece"
orange = "#b9b9b9"
green = "#b6b6b6"
cyan = "#b0b0b0"
blue = "#8d8d8d"
magenta = "#9b9b9b"
brown = "#5c5c5c"

bright_red = "#a4a4a4"
bright_yellow = "#cecece"
bright_green = "#b6b6b6"
bright_cyan = "#b0b0b0"
bright_blue = "#8d8d8d"
bright_magenta = "#9b9b9b"
