# extracted from crosswalk.jpg; tuned for readable terminal colors
mode = "dark"
accent = "#a19cde"
cursor = "#a19cde"
foreground = "#e8dce7"
background = "#2f374c"
selection_foreground = "#2f374c"
selection_background = "#a19cde"

color0 = "#3d435e"
color1 = "#e39bb1"
color2 = "#8cd98c"
color3 = "#d9d28c"
color4 = "#a19cde"
color5 = "#dca6dd"
color6 = "#91b5cc"
color7 = "#cbc3d0"
color8 = "#9293ac"
color9 = "#e9b5c5"
color10 = "#aae1aa"
color11 = "#e1dcaa"
color12 = "#bab6e5"
color13 = "#e4bde4"
color14 = "#b1ccdc"
color15 = "#e8dce7"
