# extracted from wallhaven-5ymj95-everblush.png; tuned for readable terminal colors
mode = "dark"
accent = "#71acc6"
cursor = "#71acc6"
foreground = "#f8faea"
background = "#1a2225"
selection_foreground = "#1a2225"
selection_background = "#71acc6"

color0 = "#444a4b"
color1 = "#c67171"
color2 = "#a5c4b1"
color3 = "#a6b477"
color4 = "#7ba2b4"
color5 = "#b171c6"
color6 = "#6396a5"
color7 = "#d9dccf"
color8 = "#7d827d"
color9 = "#d39696"
color10 = "#bcd2c5"
color11 = "#bcc69a"
color12 = "#9bb9c6"
color13 = "#c496d3"
color14 = "#8bb0ba"
color15 = "#f8faea"
