accent = "#b8b8b6"
cursor = "#f0f2f5"
foreground = "#f0f2f5"
background = "#0a1220"
selection_foreground = "#0a1220"
selection_background = "#f0f2f5"

color0 = "#0a1220"
color1 = "#e06b58"
color2 = "#889889"
color3 = "#b8b5a2"
color4 = "#b8b8b6"
color5 = "#e48b7a"
color6 = "#d0cac7"
color7 = "#f0f2f5"
color8 = "#555c65"
color9 = "#e06b58"
color10 = "#9eaca1"
color11 = "#c8c3b8"
color12 = "#cdcbc9"
color13 = "#f0a19a"
color14 = "#e3ddda"
color15 = "#f0f2f5"
