background = #0a1220
foreground = #f0f2f5
cursor-color = #f0f2f5
selection-background = #f0f2f5
selection-foreground = #0a1220

palette = 0=#0a1220
palette = 1=#e06b58
palette = 2=#889889
palette = 3=#b8b5a2
palette = 4=#b8b8b6
palette = 5=#e48b7a
palette = 6=#d0cac7
palette = 7=#f0f2f5
palette = 8=#555c65
palette = 9=#e06b58
palette = 10=#9eaca1
palette = 11=#c8c3b8
palette = 12=#cdcbc9
palette = 13=#f0a19a
palette = 14=#e3ddda
palette = 15=#f0f2f5

macos-icon = custom-style
macos-icon-ghost-color = #b8b8b6
macos-icon-screen-color = #0a1220
