# extracted from beach-rocks.jpg; tuned for readable terminal colors
mode = "dark"
accent = "#88aab6"
cursor = "#88aab6"
foreground = "#cdd0d1"
background = "#0e1216"
selection_foreground = "#0e1216"
selection_background = "#88aab6"

color0 = "#25292c"
color1 = "#b88b88"
color2 = "#92a991"
color3 = "#b6ae91"
color4 = "#8da4b6"
color5 = "#ab96b6"
color6 = "#89acb3"
color7 = "#b0b3b5"
color8 = "#77858b"
color9 = "#ccadaa"
color10 = "#b1c2b0"
color11 = "#cbc5b0"
color12 = "#aebeca"
color13 = "#c3b4cc"
color14 = "#aacecf"
color15 = "#cdd0d1"
